version: "3.7"
services:hahahahaha
    frontend:
        container_name: rankedio_frontend
        restart: always
        image: nginx:1.21.0-alpine
        volumes:
            - './frontend:/usr/share/nginx/html'
        ports:
            - '8081:80'
        environment: 
            - npm_config_unsafe_perm=true
        networks:
            - rankedio-network
    minecraft:
        container_name: rankedio_mc_srv
        image: itzg/minecraft-server
        ports: 
            - 25565:25565
            - 4567:4567
        environment: 
            EULA: 'TRUE'
            TYPE: 'SPIGOT'
            MEMORY: '1G'
            MAX_PLAYERS: 10
            MOTD: 'RANKED.IO - Serwer testowy'
            OPS: 'Mustafo'
            VERSION: '1.16.5'
        volumes: 
            - ./minecraft-server:/data
        stdin_open: true
        restart: always
        networks:
            - rankedio-network
    postgres:
        restart: always
        image: postgres
        environment:
            POSTGRES_DB: backend_db
            POSTGRES_USER: backend_db
            POSTGRES_PASSWORD: backend_db
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - rankedio-network
    backend:
        restart: always
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:1337
        volumes:
            - ./backend:/code
        ports: 
            - "1337:1337"
        depends_on: 
            - postgres
            - minecraft
            - frontend
        networks:
            - rankedio-network
networks: 
    rankedio-network:
        driver: bridge


