version: "3.7"
services:
    frontend:
        container_name: rankedio_frontend
        restart: always
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './frontend/source:/app'
            - '/app/node_modules'
        ports:
            - '8081:8080'
        environment: 
            - npm_config_unsafe_perm=true
    minecraft:
        container_name: rankedio_mc_srv
        image: itzg/minecraft-server
        ports: 
            - 25565:25565
        environment: 
            EULA: 'TRUE'
            TYPE: 'SPIGOT'
            MEMORY: '1G'
            MAX_PLAYERS: 10
            MOTD: 'RANKED.IO - Serwer testowy'
            OPS: 'Mustafo'
        volumes: 
            - ./minecraft-server:/data
        stdin_open: true
        restart: always
    strapi:
        image: strapi/strapi
        environment:
            DATABASE_CLIENT: postgres
            DATABASE_NAME: strapi
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
        volumes:
            - ./app:/srv/app
        ports:
            - '1337:1337'
        depends_on:
            - postgres
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: strapi
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
        volumes:
            - ./data:/var/lib/postgresql/data
networks: 
    rankedio-network:
        driver: bridge


