# Generated by Django 3.2.4 on 2021-06-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('displayName', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
