# Generated by Django 3.2.4 on 2021-06-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='EntityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityType', models.CharField(max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entityStats_on_Players', to='api_basic.players')),
            ],
        ),
    ]
