# Generated by Django 3.2.4 on 2021-06-14 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210613_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockType', models.CharField(max_length=30)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockStats_on_Players', to='api_basic.players')),
            ],
        ),
    ]
