# Generated by Django 3.2.4 on 2021-06-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_blockstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killer_on_Players', to='api_basic.players')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_on_Players', to='api_basic.players')),
            ],
        ),
    ]
